services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:80" # https://localhost:8083
    volumes:
      - .:/var/www/html
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Required for Xdebug to connect back to host
